/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Geometry, type GLTF } from 'three-stdlib'
import model from '/models/sku/coffee.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    ['material_0.008']: THREE.MeshPhysicalMaterial
  }
}

export function Coffee(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <mesh {...props}
        castShadow
        receiveShadow
        geometry={nodes.model.geometry}
      material={materials['material_0.008']}
      />

  )
}

useGLTF.preload(model)
