/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/sku/mustard.glb?url'
type GLTFResult = GLTF & {
  nodes: {
    textured: THREE.Mesh
  }
  materials: {
    ['material_0.001']: THREE.MeshPhysicalMaterial
  }
}

export function Mustard(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.textured.geometry}
        material={materials['material_0.001']}
      />
    </group>
  )
}

useGLTF.preload(model)
