/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF, Decal, RenderTexture, Text, PerspectiveCamera, useCursor, Box } from '@react-three/drei'
import {type GLTF} from 'three-stdlib'
import model from '/models/room/door.glb?url'
import handwritten_font from '/fonts/handwritten.ttf?url'
import formal_font from '/fonts/Noto_Sans,Noto_Sans_SC/Noto_Sans_SC/static/NotoSansSC-Regular.ttf?url'
import bold_formal_font from '/fonts/Noto_Sans,Noto_Sans_SC/Noto_Sans_SC/static/NotoSansSC-Bold.ttf?url'
import {useTranslation} from "react-i18next"
import { useState } from 'react'
import lang_toggle from '../../lib/glb_const'

type GLTFResult = GLTF & {
    nodes: {
        OBJ_1: THREE.Mesh
        OBJ_2: THREE.Mesh
    }
    materials: {
        Wood: THREE.MeshPhysicalMaterial
        Brass_A_5: THREE.MeshPhysicalMaterial
    }
}

const SCALE = 50
const TITLE_BRIGHTNESS = 100;
const BODY_BRIGHTNESS = 15;
const HELLO_BRIGHTNESS = 1;
const INVIS = 0

export function RedrumDoor(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(model) as GLTFResult
    const [hovered, setHovered] = useState(false)
    const { t, i18n } = useTranslation();
    useCursor(hovered)
    return (
        <group {...props} dispose={null}>
            <mesh position={[1.035, 0.948, 1.28]}>
                <Box args={[0.025, 0.008, 0.01]}
                    onClick={() => window.open("https://www.linkedin.com/in/yiyi-yan-217a7a106/", "_blank")}
                    onPointerOver={() => setHovered(true)}
                    onPointerOut={() => setHovered(false)}>
                    <meshStandardMaterial transparent opacity={INVIS} />
                </Box>
            </mesh>
            <mesh position={[0.992, 0.95, 1.28]} rotation={[0, 0, 0]}>
                <Box args={[0.02, 0.008, 0.01]}
                    onClick={() => window.open(`${lang_toggle.is_en ? "/cheshire/images/instagram.png" : "/cheshire/images/wechat.png"}`, "_blank")}
                    onPointerOver={() => setHovered(true)}
                    onPointerOut={() => setHovered(false)}>
                    <meshStandardMaterial transparent opacity={INVIS} />
                </Box>
            </mesh>
            <mesh position={[0.94, 0.953, 1.28]}>
                <Box args={[0.02, 0.008, 0.01]}
                    onPointerOver={() => setHovered(true)}
                    onPointerOut={() => setHovered(false)}
                    onClick={() => window.open("https://github.com/Rainerino", "_blank")}>
                    <meshStandardMaterial transparent opacity={INVIS} />
                </Box>
            </mesh>

            <group position={[1.65, 1.02, -2.63]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.OBJ_1.geometry}
                    material={materials.Wood}
                >
                    <Decal
                        position={[0, 0, 0.7 * SCALE]}
                        rotation={[-Math.PI / 2, Math.PI, 0]}
                        scale={[1 * SCALE, 2 * SCALE, 1 * SCALE]}
                    >
                        {/* ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789! */}
                        <meshStandardMaterial
                            transparent
                            polygonOffset
                            polygonOffsetFactor={-1}>
                            <RenderTexture attach="map" anisotropy={256}>
                                <PerspectiveCamera makeDefault manual aspect={0.5} position={[0, 0, 2]}/>
                                <ambientLight intensity={1}/>
                                <Text font={handwritten_font}
                                    color={new THREE.Color(HELLO_BRIGHTNESS, 0, 0)}
                                    position={[0, 0.6, 0]} fontSize={0.15}>
                                    H  LLO
                                </Text>
                                <Text font={handwritten_font}
                                    color={new THREE.Color(HELLO_BRIGHTNESS, 0, 0)}
                                    position={[-0.13, 0.63, 0]} rotation={[0, Math.PI, 0]}
                                    fontSize={0.15} >
                                    E
                                </Text>
                                <Text font={bold_formal_font}
                                    anchorX="left" anchorY="middle"
                                    color={new THREE.Color(TITLE_BRIGHTNESS, TITLE_BRIGHTNESS, TITLE_BRIGHTNESS)}
                                    position={[-0.28, 0.09, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.04}
                                >
                                    {t("about")}
                                </Text>
                                <Text font={formal_font}
                                    anchorX="left" anchorY="top"
                                    lineHeight={1.5}
                                    color={new THREE.Color(BODY_BRIGHTNESS, BODY_BRIGHTNESS, BODY_BRIGHTNESS)}
                                    position={[-0.28, 0.04, 0]}
                                    fontSize={0.03} >
                                    {t("about_intro")}
                                </Text>
                                <Text font={bold_formal_font}
                                    anchorX="left" anchorY="middle"
                                    color={new THREE.Color(TITLE_BRIGHTNESS, TITLE_BRIGHTNESS, TITLE_BRIGHTNESS)}
                                    position={[-0.28, -0.3, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.04}
                                >
                                    {t("social")}
                                </Text>

                                <Text
                                    font={formal_font}
                                    anchorX="left"
                                    anchorY="middle"
                                    color={new THREE.Color(BODY_BRIGHTNESS, BODY_BRIGHTNESS, BODY_BRIGHTNESS)}
                                    position={[-0.28, -0.37, 0]}
                                    rotation={[0, 0, 0]}
                                    fontSize={0.03}
                                >
                                    {t("linkedln")}
                                </Text>

                                <Text font={formal_font}
                                    anchorX="left" anchorY="middle"
                                    color={new THREE.Color(BODY_BRIGHTNESS, BODY_BRIGHTNESS, BODY_BRIGHTNESS)}
                                    position={[-0.1, -0.37, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.03}
                                >
                                    {t("sm")}
                                </Text>

                                <Text font={formal_font}
                                    anchorX="left" anchorY="middle"
                                    color={new THREE.Color(BODY_BRIGHTNESS, BODY_BRIGHTNESS, BODY_BRIGHTNESS)}
                                    position={[0.1, -0.37, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.03}
                                >
                                    {t("github")}
                                </Text>

                                <Text font={bold_formal_font}
                                    anchorX="left" anchorY="middle"
                                    color={new THREE.Color(TITLE_BRIGHTNESS, TITLE_BRIGHTNESS, TITLE_BRIGHTNESS)}
                                    position={[-0.28, -0.5, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.04}
                                >
                                    {t("contact")}
                                </Text>

                                <Text font={formal_font}
                                    anchorX="left" anchorY="top"
                                    color={new THREE.Color(BODY_BRIGHTNESS, BODY_BRIGHTNESS, BODY_BRIGHTNESS)}
                                    position={[-0.28, -0.55, 0]} rotation={[0, 0, 0]}
                                    fontSize={0.03}
                                    lineHeight={1.5}
                                >
                                    {"albert.yanyy(at)gmail.com\n+86 18957127262"}
                                </Text>
                            </RenderTexture>
                        </meshStandardMaterial>
                    </Decal>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.OBJ_2.geometry}
                    material={materials.Brass_A_5}
                />
            </group>
        </group>
    )
}

useGLTF.preload(model)