/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import {useGLTF} from '@react-three/drei'
import {type GLTF} from 'three-stdlib'
import model from '/models/es/CAT_6080_S.glb?url'

type GLTFResult = GLTF & {
    nodes: {
        Node1: THREE.Mesh
        Node10: THREE.Mesh
        Node13: THREE.Mesh
        Node14: THREE.Mesh
        Node15: THREE.Mesh
        Node16: THREE.Mesh
        Node17: THREE.Mesh
        Node18: THREE.Mesh
        Node19: THREE.Mesh
        Node2: THREE.Mesh
        Node20: THREE.Mesh
        Node21: THREE.Mesh
        Node22: THREE.Mesh
        Node23: THREE.Mesh
        Node24: THREE.Mesh
        Node25: THREE.Mesh
        Node26: THREE.Mesh
        Node27: THREE.Mesh
        Node28: THREE.Mesh
        Node29: THREE.Mesh
        Node3: THREE.Mesh
        Node30: THREE.Mesh
        Node31: THREE.Mesh
        Node32: THREE.Mesh
        Node4: THREE.Mesh
        Node5: THREE.Mesh
        Node6: THREE.Mesh
        Node7: THREE.Mesh
        Node8: THREE.Mesh
        Node9: THREE.Mesh
    }
    materials: {
        ['#333333FF.005']: THREE.MeshLambertMaterial
        ['#336633FF.005']: THREE.MeshLambertMaterial
        ['#9B7428FF.005']: THREE.MeshLambertMaterial
        ['#990000FF.005']: THREE.MeshLambertMaterial
        ['#00956EFF.005']: THREE.MeshLambertMaterial
        ['#3333FFFF.005']: THREE.MeshLambertMaterial
        ['#993333FF.005']: THREE.MeshLambertMaterial
        ['#7FA1B4FF.005']: THREE.MeshLambertMaterial
        ['#CC9933FF.005']: THREE.MeshLambertMaterial
        ['#D16A37FF.005']: THREE.MeshLambertMaterial
        ['#FFFF00FF.005']: THREE.MeshLambertMaterial
        ['#F6AE83FF.005']: THREE.MeshLambertMaterial
        ['#00FF00FF.005']: THREE.MeshLambertMaterial
        ['#6633CCFF.005']: THREE.MeshLambertMaterial
        ['#FF3AE0FF.005']: THREE.MeshLambertMaterial
        ['#FF9900FF.005']: THREE.MeshLambertMaterial
        ['#FF5050FF.005']: THREE.MeshLambertMaterial
        ['#FFBF4BFF.005']: THREE.MeshLambertMaterial
        ['#7D7D7DFF.005']: THREE.MeshLambertMaterial
        ['#CCFF33FF.005']: THREE.MeshLambertMaterial
        ['#0099FFFF.005']: THREE.MeshLambertMaterial
        ['#FF0000FF.005']: THREE.MeshLambertMaterial
        ['#97AAAEFF.005']: THREE.MeshLambertMaterial
        ['#66CCFFFF.005']: THREE.MeshLambertMaterial
        ['#006666FF.005']: THREE.MeshLambertMaterial
        ['#999999FF.005']: THREE.MeshLambertMaterial
    }
}

export function CAT6080(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF(model) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group position={[0, 10.068, 0]} rotation={[1.573, 0, 0]} scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Node1.geometry}
                    material={materials['#333333FF.005']}
                    position={[0, 0, 0.002]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node10.geometry}
                        material={materials['#336633FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node13.geometry}
                        material={materials['#9B7428FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node14.geometry}
                        material={materials['#990000FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node15.geometry}
                        material={materials['#00956EFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node16.geometry}
                        material={materials['#3333FFFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node17.geometry}
                        material={materials['#993333FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node18.geometry}
                        material={materials['#333333FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node19.geometry}
                        material={materials['#7FA1B4FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node2.geometry}
                        material={materials['#333333FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node20.geometry}
                        material={materials['#CC9933FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node21.geometry}
                        material={materials['#D16A37FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node22.geometry}
                        material={materials['#FFFF00FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node23.geometry}
                        material={materials['#F6AE83FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node24.geometry}
                        material={materials['#00FF00FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node25.geometry}
                        material={materials['#6633CCFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node26.geometry}
                        material={materials['#FF3AE0FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node27.geometry}
                        material={materials['#FF9900FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node28.geometry}
                        material={materials['#FF5050FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node29.geometry}
                        material={materials['#FFBF4BFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node3.geometry}
                        material={materials['#7D7D7DFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node30.geometry}
                        material={materials['#CCFF33FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node31.geometry}
                        material={materials['#0099FFFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node32.geometry}
                        material={materials['#FF0000FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node4.geometry}
                        material={materials['#333333FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node5.geometry}
                        material={materials['#97AAAEFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node6.geometry}
                        material={materials['#7D7D7DFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node7.geometry}
                        material={materials['#66CCFFFF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node8.geometry}
                        material={materials['#006666FF.005']}
                        position={[0, 0, 0.002]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Node9.geometry}
                        material={materials['#999999FF.005']}
                        position={[0, 0, 0.002]}
                    />
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload(model)
