/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {type GLTF} from 'three-stdlib'
import model from '/models/room/chair.glb?url'

type GLTFResult = GLTF & {
    nodes: {
        Chair: THREE.Mesh
    }
    materials: {
        ['Material.001']: THREE.MeshLambertMaterial
    }
}

export function Chair(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF(model) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair.geometry}
                material={materials['Material.001']}
                position={[0.59, 0, -0.208]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
        </group>
    )
}

useGLTF.preload(model)
