/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/tv_room/small_table.glb?url'


type GLTFResult = GLTF & {
  nodes: {
    Tavolino_quadrato_15: THREE.Mesh
    Tavolino_retangolare__040: THREE.Mesh
    Tavolino_retangolare__041: THREE.Mesh
    Tavolino_retangolare__042: THREE.Mesh
    Tavolino_retangolare__043: THREE.Mesh
    Tavolino_retangolare__044: THREE.Mesh
    Tavolino_retangolare__045: THREE.Mesh
    Tavolino_retangolare__046: THREE.Mesh
    Tavolino_retangolare__047: THREE.Mesh
    Tavolino_retangolare__048: THREE.Mesh
    Tavolino_retangolare__049: THREE.Mesh
    Tavolino_retangolare__050: THREE.Mesh
    Tavolino_retangolare__051: THREE.Mesh
    Tavolino_retangolare__052: THREE.Mesh
    Tavolino_retangolare__053: THREE.Mesh
    Tavolino_retangolare__054: THREE.Mesh
    Tavolino_retangolare__055: THREE.Mesh
    Tavolino_retangolare__056: THREE.Mesh
    Tavolino_retangolare__057: THREE.Mesh
    Tavolino_retangolare__058: THREE.Mesh
    Tavolino_retangolare__059: THREE.Mesh
    Tavolino_retangolare__060: THREE.Mesh
    Tavolino_retangolare__061: THREE.Mesh
    Tavolino_retangolare__062: THREE.Mesh
    Tavolino_retangolare__063: THREE.Mesh
    Tavolino_retangolare__074: THREE.Mesh
    Tavolino_retangolare__075: THREE.Mesh
    Tavolino_retangolare__076: THREE.Mesh
    Tavolino_retangolare__077: THREE.Mesh
  }
  materials: {
    wire_067067067: THREE.MeshPhysicalMaterial
    wire_045045045: THREE.MeshPhysicalMaterial
  }
}

export function CouchTable(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tavolino_quadrato_15.geometry}
        material={materials.wire_067067067}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__040.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__041.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__042.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__043.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__044.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__045.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__046.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__047.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__048.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__049.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__050.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__051.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__052.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__053.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__054.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__055.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__056.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__057.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__058.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__059.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__060.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__061.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__062.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__063.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__074.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__075.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__076.geometry}
          material={materials.wire_045045045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tavolino_retangolare__077.geometry}
          material={materials.wire_045045045}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
