/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/lamp2.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Node1: THREE.Mesh
    Node2: THREE.Mesh
    Node3: THREE.Mesh
  }
  materials: {
    ['#292929FF']: THREE.MeshLambertMaterial
    ['#0EAA49FF']: THREE.MeshPhysicalMaterial
    ['#C6901CFF']: THREE.MeshLambertMaterial
  }
}

export function DeskLamp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1.geometry}
        material={materials['#292929FF']}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2.geometry}
          material={materials['#0EAA49FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3.geometry}
          material={materials['#C6901CFF']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
