/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/tv_room/double_couch.glb?url'



type GLTFResult = GLTF & {
  nodes: {
    Node1: THREE.Mesh
  }
  materials: {
    couch_color: THREE.MeshLambertMaterial
  }
}

export function DoubleCouch(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1.geometry}
        material={materials.couch_color}
        scale={0.001}
      />
    </group>
  )
}

useGLTF.preload(model)
