/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/pen.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Node1: THREE.Mesh
    Node10: THREE.Mesh
    Node2: THREE.Mesh
    Node3: THREE.Mesh
    Node4: THREE.Mesh
    Node5: THREE.Mesh
    Node6: THREE.Mesh
    Node7: THREE.Mesh
    Node8: THREE.Mesh
    Node9: THREE.Mesh
  }
  materials: {
    ['#D3D6D3FF']: THREE.MeshLambertMaterial
    ['#999999FF']: THREE.MeshLambertMaterial
    ['#808080FF']: THREE.MeshLambertMaterial
    ['#A58300FF']: THREE.MeshLambertMaterial
    ['#0A7DB5FF']: THREE.MeshLambertMaterial
    ['#4C4C4CFF']: THREE.MeshLambertMaterial
    ['#895956FF']: THREE.MeshLambertMaterial
    ['#CAD1EEFF']: THREE.MeshLambertMaterial
    ['#EFEFEFFF']: THREE.MeshLambertMaterial
    ['#FFFFFFFF']: THREE.MeshLambertMaterial
  }
}

export function LamyPen(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1.geometry}
        material={materials['#D3D6D3FF']}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node10.geometry}
          material={materials['#999999FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2.geometry}
          material={materials['#808080FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3.geometry}
          material={materials['#A58300FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4.geometry}
          material={materials['#0A7DB5FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5.geometry}
          material={materials['#4C4C4CFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6.geometry}
          material={materials['#895956FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7.geometry}
          material={materials['#CAD1EEFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node8.geometry}
          material={materials['#EFEFEFFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node9.geometry}
          material={materials['#FFFFFFFF']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
