/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import station from '/models/stations/redcare_one_piece.glb?url'


  
  const STATION_MATERIAL = new THREE.MeshPhysicalMaterial({
    color: 0x888888, // light gray metallic
    metalness: 1.0, // fully metallic
    roughness: 0.9, // high roughness for coarse look
    opacity: 1.0,
    transparent: false,
    transmission: 0.0, // no transmission for metal
    clearcoat: 0.1, // minimal clearcoat for a less shiny finish
    clearcoatRoughness: 0.8, // rough clearcoat
  });



type GLTFResult = GLTF & {
  nodes: {
    redcare_01: THREE.Mesh
  }
  materials: {}
}

export function RedcareStation(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(station) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="redcare_01"
        castShadow={true}
        receiveShadow ={true}
        geometry={nodes.redcare_01.geometry}
        material={STATION_MATERIAL}
      />
    </group>
  )
}

useGLTF.preload(station)
