/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/Env2.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    Node1002: THREE.Mesh
    Node10001: THREE.Mesh
    Node2001: THREE.Mesh
    Node3001: THREE.Mesh
    Node4001: THREE.Mesh
    Node5001: THREE.Mesh
    Node6001: THREE.Mesh
    Node7001: THREE.Mesh
    Node1001: THREE.Mesh
    slap: THREE.Mesh
    Node1003: THREE.Mesh
    Node10002: THREE.Mesh
    Node11: THREE.Mesh
    Node12: THREE.Mesh
    Node13: THREE.Mesh
    Node14: THREE.Mesh
    Node15: THREE.Mesh
    Node16: THREE.Mesh
    Node17: THREE.Mesh
    Node18: THREE.Mesh
    Node2002: THREE.Mesh
    Node3002: THREE.Mesh
    Node4002: THREE.Mesh
    Node5002: THREE.Mesh
    Node6002: THREE.Mesh
    Node7002: THREE.Mesh
    Node8002: THREE.Mesh
    Node9002: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_1: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_2: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_3: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_4: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato_5: THREE.Mesh
    Node1: THREE.Mesh
    Node2: THREE.Mesh
    Node3: THREE.Mesh
    Node1004: THREE.Mesh
    Node2003: THREE.Mesh
    Node3003: THREE.Mesh
    stand: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_1: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_2: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_3: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_4: THREE.Mesh
    Table_lamp_base_3d_model_kathzerrato001_5: THREE.Mesh
    Node1005: THREE.Mesh
    Node1006: THREE.Mesh
    Node2004: THREE.Mesh
    Node1008: THREE.Mesh
    wood: THREE.Mesh
    wood003: THREE.Mesh
    wood001: THREE.Mesh
    wood002: THREE.Mesh
    wood004: THREE.Mesh
    carpet001: THREE.Mesh
    Node1010: THREE.Mesh
  }
  materials: {
    ['#BB935CFF.003']: THREE.MeshLambertMaterial
    ['#000000FF.003']: THREE.MeshLambertMaterial
    ['x1.002']: THREE.MeshLambertMaterial
    ['Material.007']: THREE.MeshLambertMaterial
    ['#D7D0C0FF']: THREE.MeshLambertMaterial
    ['#F7E099FF']: THREE.MeshLambertMaterial
    ['#E5E5E5FF']: THREE.MeshLambertMaterial
    ['#57D669FF']: THREE.MeshLambertMaterial
    ['#CAD1EEFF']: THREE.MeshLambertMaterial
    ['#DBDBDBFF']: THREE.MeshLambertMaterial
    ['#C2662EFF']: THREE.MeshLambertMaterial
    ['#FFFFFFFF.003']: THREE.MeshLambertMaterial
    ['#A58300FF']: THREE.MeshLambertMaterial
    ['#1A1A1AFF']: THREE.MeshLambertMaterial
    ['#49A954FF']: THREE.MeshLambertMaterial
    ['Aluminum_-_Polished']: THREE.MeshPhysicalMaterial
    ['Fabric_(Generic)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Black)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Blue)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Yellow)']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Dark_Grey)']: THREE.MeshPhysicalMaterial
    ['#181818FF.002']: THREE.MeshLambertMaterial
    ['#F5F5F2FF.001']: THREE.MeshPhysicalMaterial
    ['#F4F4F5FF.001']: THREE.MeshLambertMaterial
    ['#181818FF.003']: THREE.MeshLambertMaterial
    ['#F5F5F2FF.002']: THREE.MeshPhysicalMaterial
    ['#F4F4F5FF.002']: THREE.MeshLambertMaterial
    ['Material.008']: THREE.MeshLambertMaterial
    ['Aluminum_-_Polished.001']: THREE.MeshPhysicalMaterial
    ['Fabric_(Generic).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Black).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Blue).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Enamel_Glossy_(Yellow).001']: THREE.MeshPhysicalMaterial
    ['Paint_-_Metallic_(Dark_Grey).001']: THREE.MeshPhysicalMaterial
    ['#000000FF']: THREE.MeshLambertMaterial
    ['#FFFFFFFF']: THREE.MeshLambertMaterial
    ['#4C4C4CFF']: THREE.MeshLambertMaterial
    ['#E0DFDBFF.001']: THREE.MeshLambertMaterial
    ['Material.003']: THREE.MeshLambertMaterial
    ['Material.009']: THREE.MeshLambertMaterial
    ['Material.001']: THREE.MeshLambertMaterial
    ['Material.004']: THREE.MeshLambertMaterial
    ['Material.011']: THREE.MeshLambertMaterial
    ['Material.012']: THREE.MeshLambertMaterial
    ['#CAD1EEFF.001']: THREE.MeshLambertMaterial
  }
}

export function Room2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.498, -0.047, 2.728]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1002.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node10001.geometry}
          material={materials['#000000FF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6001.geometry}
          material={materials['#BB935CFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7001.geometry}
          material={materials['#BB935CFF.003']}
        />
      </group>
      <group position={[0.461, 0.072, -1.907]} rotation={[1.561, 0.003, 0.787]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1001.geometry}
          material={materials['x1.002']}
          position={[-0.01, -0.005, 1.122]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.slap.geometry}
        material={materials['Material.007']}
        position={[1.058, 0.003, -2.503]}
        rotation={[1.571, -0.002, -1.562]}
        scale={[3, 3, 2]}
      />
      <group position={[0.79, 0.619, 2.299]} rotation={[Math.PI / 2, 0, 1.647]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato.geometry}
          material={materials['Aluminum_-_Polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_1.geometry}
          material={materials['Fabric_(Generic)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_2.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Black)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_3.geometry}
          material={materials['Paint_-_Metallic_(Blue)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_4.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Yellow)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato_5.geometry}
          material={materials['Paint_-_Metallic_(Dark_Grey)']}
        />
      </group>
      <group rotation={[1.571, -0.003, -1.631]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1.geometry}
          material={materials['#181818FF.002']}
          position={[-1375.709, 1021.255, -1271.302]}
          rotation={[0, 0, 0.06]}
          scale={[2.31, 0.76, 1.45]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node2.geometry}
            material={materials['#F5F5F2FF.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node3.geometry}
            material={materials['#F4F4F5FF.001']}
          />
        </mesh>
      </group>
      <group position={[-1.781, 0.951, 2.655]} rotation={[1.553, 0, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1004.geometry}
          material={materials['#181818FF.003']}
          position={[0, -12.745, -0.23]}
          scale={[0.83, 1.34, 1.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node2003.geometry}
            material={materials['#F5F5F2FF.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node3003.geometry}
            material={materials['#F4F4F5FF.002']}
          />
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand.geometry}
        material={materials['Material.008']}
        position={[-2.292, 0.002, 2.249]}
        scale={[0.012, 0.01, 0.012]}
      />
      <group position={[-2.297, 0.631, 2.265]} rotation={[Math.PI / 2, 0, 1.866]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001.geometry}
          material={materials['Aluminum_-_Polished.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_1.geometry}
          material={materials['Fabric_(Generic).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_2.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Black).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_3.geometry}
          material={materials['Paint_-_Metallic_(Blue).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_4.geometry}
          material={materials['Paint_-_Enamel_Glossy_(Yellow).001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_lamp_base_3d_model_kathzerrato001_5.geometry}
          material={materials['Paint_-_Metallic_(Dark_Grey).001']}
        />
      </group>
      <group position={[-1.738, 0, -2.438]} rotation={[1.571, 0, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1005.geometry}
          material={materials['#000000FF']}
          position={[-285.339, -25.697, 0.012]}
          scale={[1.51, 1.23, 1.68]}
        />
      </group>
      <group position={[0, 0.892, 1.537]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1006.geometry}
          material={materials['#FFFFFFFF']}
          position={[56.457, -308.229, 759.251]}
          rotation={[-Math.PI, 1.569, -Math.PI]}
          scale={[1, 0.64, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Node2004.geometry}
            material={materials['#4C4C4CFF']}
          />
        </mesh>
      </group>
      <group position={[0.311, 0.392, -0.216]} rotation={[-1.683, 0.224, 0.468]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1008.geometry}
          material={materials['#E0DFDBFF.001']}
          position={[-4.671, -0.005, 18.31]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood.geometry}
        material={materials['Material.003']}
        position={[0.813, 0.2, -0.58]}
        rotation={[-2.031, 0.715, 0.662]}
        scale={[0.46, 0.74, 0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood003.geometry}
        material={materials['Material.009']}
        position={[0.58, 0.29, -0.935]}
        rotation={[1.558, -0.149, -0.509]}
        scale={[0.4, 0.6, 0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood001.geometry}
        material={materials['Material.001']}
        position={[0.691, 0.205, -0.551]}
        rotation={[-1.502, -0.191, 0.464]}
        scale={[0.55, 0.71, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood002.geometry}
        material={materials['Material.004']}
        position={[0.569, 0.246, -0.494]}
        rotation={[0.916, -0.932, 2.415]}
        scale={[0.45, 0.6, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood004.geometry}
        material={materials['Material.011']}
        position={[0.626, 0.287, -0.502]}
        rotation={[-1.368, -0.353, 0.329]}
        scale={[0.45, 0.6, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carpet001.geometry}
        material={materials['Material.012']}
        position={[0.119, 0.02, -0.92]}
        rotation={[0, -0.734, -Math.PI / 2]}
        scale={[0.5, 3, 3]}
      />
      <group position={[0, 0.032, -0.655]} rotation={[1.567, 0, 1.25]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node1010.geometry}
          material={materials['#CAD1EEFF.001']}
          position={[63.956, 266.577, 9.98]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node1003.geometry}
        material={materials['#D7D0C0FF']}
        position={[0.115, 0.674, 2.295]}
        rotation={[1.578, -0.003, 2.741]}
        scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node10002.geometry}
          material={materials['#F7E099FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node11.geometry}
          material={materials['#E5E5E5FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node12.geometry}
          material={materials['#57D669FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node13.geometry}
          material={materials['#CAD1EEFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node14.geometry}
          material={materials['#DBDBDBFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node15.geometry}
          material={materials['#C2662EFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node16.geometry}
          material={materials['#FFFFFFFF.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node17.geometry}
          material={materials['#A58300FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node18.geometry}
          material={materials['#1A1A1AFF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node2002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node3002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node4002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node5002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node6002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node7002.geometry}
          material={materials['#D7D0C0FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node8002.geometry}
          material={materials['#49A954FF']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Node9002.geometry}
          material={materials['#D7D0C0FF']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(model)
