/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/tv_room/single_couch.glb?url'


type GLTFResult = GLTF & {
  nodes: {
    sofa002: THREE.Mesh
    sofa002_1: THREE.Mesh
    sofa002_2: THREE.Mesh
    sofa002_3: THREE.Mesh
  }
  materials: {
    ['wire_177028149.002']: THREE.MeshPhysicalMaterial
    wire_225088199: THREE.MeshPhysicalMaterial
    wire_224086086: THREE.MeshPhysicalMaterial
    wire_008110135: THREE.MeshPhysicalMaterial
  }
}

export function SingleCouch(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.546, 0, -0.448]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sofa002.geometry}
          material={materials['wire_177028149.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sofa002_1.geometry}
          material={materials.wire_225088199}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sofa002_2.geometry}
          material={materials.wire_224086086}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sofa002_3.geometry}
          material={materials.wire_008110135}
        />
      </group>
    </group>
  )
}

useGLTF.preload(model)
