/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/tv_room/old_tv.glb?url'


type GLTFResult = GLTF & {
  nodes: {
    Retro_Television003: THREE.Mesh
    Retro_Television003_1: THREE.Mesh
    Retro_Television003_2: THREE.Mesh
    Retro_Television003_3: THREE.Mesh
    Retro_Television003_4: THREE.Mesh
    Retro_Television003_5: THREE.Mesh
    Retro_Television003_6: THREE.Mesh
    Retro_Television003_7: THREE.Mesh
    Retro_Television003_8: THREE.Mesh
    Retro_Television003_9: THREE.Mesh
    Retro_Television003_10: THREE.Mesh
    Retro_Television003_11: THREE.Mesh
    Retro_Television003_12: THREE.Mesh
  }
  materials: {
    ['wire_087225198.003']: THREE.MeshPhysicalMaterial
    ['METAL__Smooth__Chrome_Polished.003']: THREE.MeshPhysicalMaterial
    ['Screen.003']: THREE.MeshPhysicalMaterial
    ['black_front.003']: THREE.MeshPhysicalMaterial
    ['metal_screen.003']: THREE.MeshPhysicalMaterial
    ['PLASTIC__PVC__Opaque_Black.003']: THREE.MeshPhysicalMaterial
    ['PLASTIC__PVC__Opaque_White.003']: THREE.MeshPhysicalMaterial
    ['wood.003']: THREE.MeshPhysicalMaterial
    ['PLASTIC__PVC_Foam_Board__White.003']: THREE.MeshPhysicalMaterial
    ['PLASTIC__PVC_Foam_Board__Red.003']: THREE.MeshPhysicalMaterial
    ['PLASTIC__PVC_Foam_Board__Dark_Blue.003']: THREE.MeshPhysicalMaterial
    ['METAL__Smooth__Brass_Antique.003']: THREE.MeshPhysicalMaterial
    ['wire_143225087.003']: THREE.MeshPhysicalMaterial
  }
}

export function OldTV(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.551, 0.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003.geometry}
          material={materials['wire_087225198.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_1.geometry}
          material={materials['METAL__Smooth__Chrome_Polished.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_2.geometry}
          material={materials['Screen.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_3.geometry}
          material={materials['black_front.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_4.geometry}
          material={materials['metal_screen.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_5.geometry}
          material={materials['PLASTIC__PVC__Opaque_Black.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_6.geometry}
          material={materials['PLASTIC__PVC__Opaque_White.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_7.geometry}
          material={materials['wood.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_8.geometry}
          material={materials['PLASTIC__PVC_Foam_Board__White.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_9.geometry}
          material={materials['PLASTIC__PVC_Foam_Board__Red.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_10.geometry}
          material={materials['PLASTIC__PVC_Foam_Board__Dark_Blue.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_11.geometry}
          material={materials['METAL__Smooth__Brass_Antique.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retro_Television003_12.geometry}
          material={materials['wire_143225087.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload(model)
