/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import model from '/models/tv_room/TVRoom.glb?url'
import { type GLTF } from 'three-stdlib'
import * as THREE from 'three'

type GLTFResult = GLTF & {
    nodes: {
        Node1001: THREE.Mesh
        sofa003_1: THREE.Mesh
        sofa003_2: THREE.Mesh
        sofa003_3: THREE.Mesh
        sofa003_4: THREE.Mesh
        Retro_Television002: THREE.Mesh
        Retro_Television002_1: THREE.Mesh
        Retro_Television002_2: THREE.Mesh
        Retro_Television002_3: THREE.Mesh
        Retro_Television002_4: THREE.Mesh
        Retro_Television002_5: THREE.Mesh
        Retro_Television002_6: THREE.Mesh
        Retro_Television002_7: THREE.Mesh
        Retro_Television002_8: THREE.Mesh
        Retro_Television002_9: THREE.Mesh
        Retro_Television002_10: THREE.Mesh
        Retro_Television002_11: THREE.Mesh
        Retro_Television002_12: THREE.Mesh
        Tavolino_quadrato_15: THREE.Mesh
        Tavolino_retangolare__040: THREE.Mesh
        Tavolino_retangolare__041: THREE.Mesh
        Tavolino_retangolare__042: THREE.Mesh
        Tavolino_retangolare__043: THREE.Mesh
        Tavolino_retangolare__044: THREE.Mesh
        Tavolino_retangolare__045: THREE.Mesh
        Tavolino_retangolare__046: THREE.Mesh
        Tavolino_retangolare__047: THREE.Mesh
        Tavolino_retangolare__048: THREE.Mesh
        Tavolino_retangolare__049: THREE.Mesh
        Tavolino_retangolare__050: THREE.Mesh
        Tavolino_retangolare__051: THREE.Mesh
        Tavolino_retangolare__056: THREE.Mesh
        Tavolino_retangolare__061: THREE.Mesh
        sofa005: THREE.Mesh
        sofa005_1: THREE.Mesh
        sofa005_2: THREE.Mesh
        sofa005_3: THREE.Mesh
    }
    materials: {
        ['#59411CFF.004']: THREE.MeshLambertMaterial
        ['wire_177028149.003']: THREE.MeshLambertMaterial
        ['wire_225088199.002']: THREE.MeshPhysicalMaterial
        ['wire_224086086.002']: THREE.MeshPhysicalMaterial
        ['wire_008110135.002']: THREE.MeshPhysicalMaterial
        ['wire_087225198.002']: THREE.MeshPhysicalMaterial
        ['METAL__Smooth__Chrome_Polished.002']: THREE.MeshPhysicalMaterial
        ['Screen.002']: THREE.MeshPhysicalMaterial
        ['black_front.002']: THREE.MeshPhysicalMaterial
        ['metal_screen.002']: THREE.MeshPhysicalMaterial
        ['PLASTIC__PVC__Opaque_Black.002']: THREE.MeshPhysicalMaterial
        ['PLASTIC__PVC__Opaque_White.002']: THREE.MeshPhysicalMaterial
        ['wood.002']: THREE.MeshPhysicalMaterial
        ['PLASTIC__PVC_Foam_Board__White.002']: THREE.MeshPhysicalMaterial
        ['PLASTIC__PVC_Foam_Board__Red.002']: THREE.MeshPhysicalMaterial
        ['PLASTIC__PVC_Foam_Board__Dark_Blue.002']: THREE.MeshPhysicalMaterial
        ['METAL__Smooth__Brass_Antique.002']: THREE.MeshPhysicalMaterial
        ['wire_143225087.002']: THREE.MeshPhysicalMaterial
        ['wire_067067067.001']: THREE.MeshPhysicalMaterial
        ['wire_177028149.006']: THREE.MeshLambertMaterial
        ['wire_225088199.005']: THREE.MeshPhysicalMaterial
        ['wire_224086086.005']: THREE.MeshPhysicalMaterial
        ['wire_008110135.005']: THREE.MeshPhysicalMaterial
    }
}

export function TVRoom(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(model) as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group position={[-0.47, 0, -0.526]} scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Node1001.geometry}
                    material={materials['#59411CFF.004']}
                    position={[1903.986, 0, -1509.709]}
                    rotation={[-Math.PI, 0.003, -Math.PI]}
                />
            </group>
            <group position={[-1.001, 0, -2.705]} rotation={[Math.PI / 2, 0, -1.576]} scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa003_1.geometry}
                    material={materials['wire_177028149.003']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa003_2.geometry}
                    material={materials['wire_225088199.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa003_3.geometry}
                    material={materials['wire_224086086.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa003_4.geometry}
                    material={materials['wire_008110135.002']}
                />
            </group>
            <group position={[0, 0.551, 0.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.003}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002.geometry}
                    material={materials['wire_087225198.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_1.geometry}
                    material={materials['METAL__Smooth__Chrome_Polished.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_2.geometry}
                    material={materials['Screen.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_3.geometry}
                    material={materials['black_front.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_4.geometry}
                    material={materials['metal_screen.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_5.geometry}
                    material={materials['PLASTIC__PVC__Opaque_Black.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_6.geometry}
                    material={materials['PLASTIC__PVC__Opaque_White.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_7.geometry}
                    material={materials['wood.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_8.geometry}
                    material={materials['PLASTIC__PVC_Foam_Board__White.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_9.geometry}
                    material={materials['PLASTIC__PVC_Foam_Board__Red.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_10.geometry}
                    material={materials['PLASTIC__PVC_Foam_Board__Dark_Blue.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_11.geometry}
                    material={materials['METAL__Smooth__Brass_Antique.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Retro_Television002_12.geometry}
                    material={materials['wire_143225087.002']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tavolino_quadrato_15.geometry}
                material={materials['wire_067067067.001']}
                position={[-0.871, 0, -1.304]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__040.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__041.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__042.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__043.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__044.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__045.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__046.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__047.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__048.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__049.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__050.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__051.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__056.geometry}
                    material={materials['wire_067067067.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tavolino_retangolare__061.geometry}
                    material={materials['wire_067067067.001']}
                />
            </mesh>
            <group position={[-1.001, 0, -4.118]} rotation={[Math.PI / 2, 0, -1.576]} scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa005.geometry}
                    material={materials['wire_177028149.006']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa005_1.geometry}
                    material={materials['wire_225088199.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa005_2.geometry}
                    material={materials['wire_224086086.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.sofa005_3.geometry}
                    material={materials['wire_008110135.005']}
                />
            </group>
        </group>
    )
}

useGLTF.preload(model)
