/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import model from '/models/room/wood_desk.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    obj003: THREE.Mesh
    obj003_1: THREE.Mesh
    obj003_2: THREE.Mesh
    obj003_3: THREE.Mesh
    obj003_4: THREE.Mesh
    obj003_5: THREE.Mesh
    obj003_6: THREE.Mesh
    obj003_7: THREE.Mesh
    obj003_8: THREE.Mesh
    obj003_9: THREE.Mesh
    obj003_10: THREE.Mesh
    obj003_11: THREE.Mesh
    obj003_12: THREE.Mesh
    obj003_13: THREE.Mesh
    obj003_14: THREE.Mesh
    obj003_15: THREE.Mesh
    obj003_16: THREE.Mesh
    obj003_17: THREE.Mesh
    obj003_18: THREE.Mesh
  }
  materials: {
    ['Mat.003']: THREE.MeshPhysicalMaterial
    ['Mat_1.003']: THREE.MeshPhysicalMaterial
    ['Mat_2.003']: THREE.MeshPhysicalMaterial
    ['Mat_3.003']: THREE.MeshPhysicalMaterial
    ['Latun2.003']: THREE.MeshPhysicalMaterial
    ['Wood_light.003']: THREE.MeshPhysicalMaterial
    ['Mat_4.003']: THREE.MeshPhysicalMaterial
    ['Mat_5.003']: THREE.MeshPhysicalMaterial
    ['Mat_8.003']: THREE.MeshPhysicalMaterial
    ['Mat_9.003']: THREE.MeshPhysicalMaterial
    ['Mat_10.003']: THREE.MeshPhysicalMaterial
    ['Mat_11.003']: THREE.MeshPhysicalMaterial
    ['Mat_12.003']: THREE.MeshPhysicalMaterial
    ['Mat_13.003']: THREE.MeshPhysicalMaterial
    ['Mat_14.003']: THREE.MeshPhysicalMaterial
    ['Mat_15.003']: THREE.MeshPhysicalMaterial
    ['Mat_16.003']: THREE.MeshPhysicalMaterial
    ['Mat_17.003']: THREE.MeshPhysicalMaterial
    ['Mat_18.003']: THREE.MeshPhysicalMaterial
  }
}

export function WoodenDesk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(model) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.432, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003.geometry}
          material={materials['Mat.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_1.geometry}
          material={materials['Mat_1.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_2.geometry}
          material={materials['Mat_2.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_3.geometry}
          material={materials['Mat_3.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_4.geometry}
          material={materials['Latun2.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_5.geometry}
          material={materials['Wood_light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_6.geometry}
          material={materials['Mat_4.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_7.geometry}
          material={materials['Mat_5.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_8.geometry}
          material={materials['Mat_8.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_9.geometry}
          material={materials['Mat_9.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_10.geometry}
          material={materials['Mat_10.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_11.geometry}
          material={materials['Mat_11.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_12.geometry}
          material={materials['Mat_12.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_13.geometry}
          material={materials['Mat_13.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_14.geometry}
          material={materials['Mat_14.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_15.geometry}
          material={materials['Mat_15.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_16.geometry}
          material={materials['Mat_16.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_17.geometry}
          material={materials['Mat_17.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.obj003_18.geometry}
          material={materials['Mat_18.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload(model)
